version: '3.8'

# Portainer için etiketler
x-portainer:
  project-name: "erci-sinav-programi"
  description: "Erci Sınav Programı - Next.js Uygulaması (Production)"

services:
  app:
    container_name: erci-sinav-programi
    # Using image from Docker Hub
    image: necdetoskay/erci-sinav-programi:latest
    labels:
      - "com.docker.compose.project=erci-sinav-programi"
      - "com.docker.compose.service=app"
    restart: always
    ports:
      - "3001:3000" # Host port 3001 mapped to container port 3000
    environment:
      - NODE_ENV=production # Üretim moduna ayarlandı
      - DATABASE_URL=postgresql://postgres:P@ssw0rd@db:5432/postgres?schema=public
      - JWT_SECRET=cpFZHH5zLazWQ0n5+iq+Fmk0AVS1j6fd/tRbai7suMQ= # JWT için güvenli anahtar
      - REFRESH_TOKEN_SECRET=cpFZHH5zLazWQ0n5+iq+Fmk0AVS1j6fd/tRbai7suMQ= # Refresh token için güvenli anahtar
      - ACCESS_TOKEN_EXPIRES_IN=15m # Access token süresi
      - REFRESH_TOKEN_EXPIRES_IN=7d # Refresh token süresi
      - NEXT_PUBLIC_APP_URL=http://localhost:3001 # Dış erişim URL'i
      - ADMIN_PASSWORD=Bi41*42* # Admin şifresi
    depends_on:
      db:
        condition: service_healthy
    networks:
      - app-network
    volumes:
      - persistent-data-prod-uploads:/app/uploads
      - ./logs:/app/logs
    # Entrypoint olarak init-admin.sh kullanılıyor
    # Bu script veritabanı migrasyonlarını çalıştırır ve admin kullanıcısını oluşturur
    entrypoint: ["/bin/sh", "/app/db/init-scripts/init-admin.sh"]
    command: ["node", "server.js"]

  db:
    container_name: erci-sinav-db
    image: postgres:15-alpine
    labels:
      - "com.docker.compose.project=erci-sinav-programi"
      - "com.docker.compose.service=db"
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=P@ssw0rd
      - POSTGRES_DB=postgres
    volumes:
      - persistent-data-prod-postgres:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d postgres"]
      interval: 5s
      timeout: 3s
      retries: 5
    networks:
      - app-network

  pgadmin:
    container_name: erci-sinav-pgadmin
    image: dpage/pgadmin4
    labels:
      - "com.docker.compose.project=erci-sinav-programi"
      - "com.docker.compose.service=pgadmin"
    restart: always
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@example.com
      - PGADMIN_DEFAULT_PASSWORD=admin
      - PGADMIN_LISTEN_PORT=80
    ports:
      - "5050:80" # Production ortamında pgAdmin'e dışarıdan erişim için port açıldı
    volumes:
      - persistent-data-prod-pgadmin:/var/lib/pgadmin
    depends_on:
      - db
    networks:
      - app-network

volumes:
  persistent-data-prod-postgres:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ./persistent-data-prod/postgres
  persistent-data-prod-pgadmin:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ./persistent-data-prod/pgadmin
  persistent-data-prod-uploads:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ./persistent-data-prod/uploads

networks:
  app-network:
    driver: bridge
