version: "3.8"

# Portainer için etiketler
x-portainer:
  project-name: "erci-sinav-programi-dev"
  description: "Erci Sınav Programı - Geliştirme Ortamı"

services:
  db:
    container_name: erci-sinav-db
    image: postgres:16-alpine
    labels:
      - "com.docker.compose.project=erci-sinav-programi"
      - "com.docker.compose.service=db"
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=P@ssw0rd
      - POSTGRES_DB=postgres
    ports:
      - "5432:5432"
    volumes:
      - ./persistent-data-dev/postgres:/var/lib/postgresql/data:delegated
    command: ["postgres", "-c", "log_statement=all", "-c", "log_connections=on"]
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d postgres"]
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 30s
    networks:
      - app-network

  pgadmin:
    container_name: erci-sinav-pgadmin
    image: dpage/pgadmin4
    labels:
      - "com.docker.compose.project=erci-sinav-programi"
      - "com.docker.compose.service=pgadmin"
    restart: always
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@example.com
      - PGADMIN_DEFAULT_PASSWORD=admin
      - PGADMIN_LISTEN_PORT=80
    ports:
      - "8080:80"
    volumes:
      - ./persistent-data-dev/pgadmin:/var/lib/pgadmin:delegated
    depends_on:
      - db
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
