version: '3.8'

services:
  # Frontend (React) uygulaması
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: kentwebadmin-frontend
    restart: unless-stopped
    ports:
      - "8080:80"
    depends_on:
      - api
    networks:
      - kentwebadmin-network

  # Kentkonut Web uygulaması
  kentkonut-web:
    build:
      context: ../kentkonut-kurumsal/kentkonut-web
      dockerfile: Dockerfile
    container_name: kentkonut-web
    restart: unless-stopped
    ports:
      - "3000:80"
    networks:
      - kentwebadmin-network

  # Basit API servisi (bcryptjs ile)
  api:
    build:
      context: ./server
      dockerfile: Dockerfile
    container_name: kentwebadmin-api
    restart: unless-stopped
    ports:
      - "5000:5000"
    environment:
      - PORT=5000
      - JWT_SECRET=SuPeR_sEcUrE_jWt_sEcReT_kEy_123456
      - JWT_ACCESS_EXPIRATION=15m
      - JWT_REFRESH_EXPIRATION=7d
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_NAME=kentwebadmin
      - DB_USER=postgres
      - DB_PASSWORD=postgres
      - CORS_ORIGIN=http://localhost:8080,http://frontend,http://127.0.0.1:8080
    depends_on:
      - postgres
    networks:
      - kentwebadmin-network

  # PostgreSQL veritabanı
  postgres:
    image: postgres:15-alpine
    container_name: kentwebadmin-postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: kentwebadmin
      PGDATA: /var/lib/postgresql/data/pgdata
    ports:
      - "5433:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - kentwebadmin-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  # pgAdmin panel (veritabanı yönetimi için)
  pgadmin:
    image: dpage/pgadmin4
    container_name: kentwebadmin-pgadmin
    restart: unless-stopped
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@kentwebadmin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"
    volumes:
      - pgadmin-data:/var/lib/pgadmin
    depends_on:
      - postgres
    networks:
      - kentwebadmin-network

volumes:
  postgres-data:
  pgadmin-data:

networks:
  kentwebadmin-network:
    driver: bridge 